OPENAI_API_KEY="your-deepseek-key"
OPENAI_API_TYPE="openai"
AZURE_API_BASE="https://api.deepseek.com"
ACCESS_TOKEN="hf-your-access-token"
LOCAL_EMBEDDING_MODEL_WEIGHTS_DIR="dir-to-your-embedding-weights"
LOCAL_RERANKER_WEIGHTS_DIR="dir-to-your-reranker-weights"
DOC_DIR="dir-to-your-data"